---
title: "flat_export_results_4.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(utils)

```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


```{r developpement}
string <- "blablabla"
if (isFALSE(as.character(string))) {
  stop("Le chemin doit être une chaine de caractère")
} else{
  write.csv(iris, string)
}
```

    
```{r function-save_as_csv}
#' Une fonction qui prend en paramètres un jeu de données et une chaîne de caractères qui correspond au chemin du fichier qui doit être créé  permet d’enregistrer le jeu de données en csv avec la fonction write.csv2() du package {utils} au chemin spécifié renvoie en sortie le chemin complet du csv créé
#' 
#' Description
#' 
#' @param data un datafram
#' @param string un chemin
#'
#' @return
#' 
#' @export
save_as_csv <- function(data, string, ...) {
  if (isFALSE(inherits(string, "character"))) {
    stop("Le chemin doit être une chaine de caractère")
  } 
  if (isFALSE(inherits(data, "data.frame"))) {
    stop("Les données doivent être sous forme de dataframe")
  }
  else {
    write.csv(data, string, ...)
  }
}
```
  
```{r example-save_as_csv}
mon_dossier_temp_aleatoire <- tempfile(pattern = "toto")
dir.create(mon_dossier_temp_aleatoire) # crée le dossier temporaire
file.create(file.path(mon_dossier_temp_aleatoire, save_as_csv(iris, "blabla")))
```
  
```{r tests-save_as_csv}
test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function")) 
})
test_that("save_as_csv works", {
  expect_error(save_as_csv(iris,2)) 
})
test_that("save_as_csv works", {
  expect_error(save_as_csv(2,"blabla")) 
})
test_that("save_as_csv works", {
  expect_error(save_as_csv(2,2)) 
}
)


```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_export_results_4.Rmd",
  vignette_name = "Exporter les résultats"
)
```
         
