---
title: "flat_first.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(glue)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## Affiche un message avec le nombre de lignes
 Affichage d'un message contenant le nombre de lignes d'un dataframe avec la fonction 'get_df_nrows()'.

```{r development2}
data <- mtcars
message(glue("Le dataframe se compose de {nrow(data)} lignes"))
```


# get_df_nrows
    
```{r function-get_df_nrows}
#' Fonction qui affiche le nombre de lignes
#' 
#' @param data le data frame qui est utilisé
#'
#' @importFrom  glue glue
#' 
#' @return un numerique (nombre de lignes) et un message 
#' 
#' @export
get_df_nrows <- function(data){
  nrows <- nrow(data)
  message(glue("Le dataframe se compose de {nrows} lignes"))
  return(nrows)
}
```
  
```{r example-get_df_nrows}
get_df_nrows(data=iris)
get_df_nrows(data=mtcars)
```
  
```{r tests-get_df_nrows}
test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(data = mtcars),
    regexp = "Le dataframe se compose de 32 lignes"
  )
})
``` 

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_get_info.Rmd",
               vignette_name = "Get info about the dataset")
```

