# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_presence_of_required_columns works", {
  expect_true(check_presence_of_required_columns(squirrels::data_demo_squirrels)
) 
})
