# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("filter_squirrels_data_based_on_integrity works", {
  expect_message(filter_squirrels_data_based_on_integrity(squirrels::data_demo_squirrels)
, "df_valid_data") 
})
