# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_plus_in_primary_fur_color works", {
  mymtcars <- head(iris)
  expect_true(inherits(check_plus_in_primary_fur_color, "function")) 
  expect_error(check_plus_in_primary_fur_color(mymtcars$Sepal.Width))
})
