# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

test_that("get_df_nrows works", {
  expect_message(
    object = get_df_nrows(data = mtcars),
    regexp = "Le dataframe se compose de 32 lignes"
  )
})
