# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Fonction qui vérifie si les coordonnées sont correctes
#' 
#' 
#' 
#' @return
#' 
#' @export
#' @examples
#' check_coordinates()
check_coordinates <- function(){
    
}
