# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Vérifie que toutes les colonnes existent
#' 
#' @param un data frame
#' 
#' @return un booléen TRUE si tout est OK, et un message d’erreur dans le cas contraire
#' 
#' @export
#' @examples
#' check_presence_of_required_columns(squirrels::data_demo_squirrels)
#' check_presence_of_required_columns(mtcars)
#'
check_presence_of_required_columns <- function(data){
    isTRUE(all(names(data) %in% c("primary_fur_color", "long", "lat")))
  }
