# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Fonction qui vérifie que la couleur entrée est bien un chaine de caractère 
#' 
#' @param vec un vecteur de couleur
#'
#' @importFrom  stringr str_detect
#' 
#' @return une erreur si le vecteur n’est pas de type “character”
#' 
#' @export
#' @examples
#' mymtcars <- head(iris)
#' check_plus_in_primary_fur_color(as.character(mymtcars$Species))
check_plus_in_primary_fur_color <- function(primary_fur_color) {
  if(isFALSE(is.character(primary_fur_color))) { stop("Le vecteur n'est pas une chaine de caractère")}
  colors_are_ok <- !str_detect(string = primary_fur_color, pattern = "\\+")
  return(colors_are_ok)
}
