# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Vérifie l'intégrité d'un data frame 
#' 
#' @param data un data frame
#' 
#' @return un message : df_valid_data : données “valides” au niveau des couleurs et des coordonnées, df_invalid_data : données “invalides” au niveau des couleurs et des coordonnées, df_missing_data : données pour lesquelles la validité n’a pu être vérifiée
#' 
#' @export
#' @examples
#' filter_squirrels_data_based_on_integrity(squirrels::data_demo_squirrels)
filter_squirrels_data_based_on_integrity <- function(data) {
  if (isTRUE(all(
    check_presence_of_required_columns(data),
    check_plus_in_primary_fur_color(data$primary_fur_color)
  ))) {
    message("df_valid_data")
  } else {
    if ((isFALSE(
      all(
        check_presence_of_required_columns(data),
        check_plus_in_primary_fur_color(data$primary_fur_color)
      )
    ))) {
      message("df_invalid_data")
    }
  }
}
