# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

#' Fonction qui affiche le nombre de lignes
#' 
#' @param data le data frame qui est utilisé
#'
#' @importFrom  glue glue
#' 
#' @return un numerique (nombre de lignes) et un message 
#' 
#' @export
#' @examples
#' get_df_nrows(data=iris)
#' get_df_nrows(data=mtcars)
get_df_nrows <- function(data){
  nrows <- nrow(data)
  message(glue("Le dataframe se compose de {nrows} lignes"))
  return(nrows)
}
