# WARNING - Generated by {fusen} from dev/flat_export_results_4.Rmd: do not edit by hand

#' Une fonction qui prend en paramètres un jeu de données et une chaîne de caractères qui correspond au chemin du fichier qui doit être créé  permet d’enregistrer le jeu de données en csv avec la fonction write.csv2() du package {utils} au chemin spécifié renvoie en sortie le chemin complet du csv créé
#' 
#' Description
#' 
#' @param data un datafram
#' @param string un chemin
#'
#' @return
#' 
#' @export
#' @examples
#' mon_dossier_temp_aleatoire <- tempfile(pattern = "toto")
#' dir.create(mon_dossier_temp_aleatoire) # crée le dossier temporaire
#' file.create(file.path(mon_dossier_temp_aleatoire, save_as_csv(iris, "blabla")))
save_as_csv <- function(data, string, ...) {
  if (isFALSE(inherits(string, "character"))) {
    stop("Le chemin doit être une chaine de caractère")
  } 
  if (isFALSE(inherits(data, "data.frame"))) {
    stop("Les données doivent être sous forme de dataframe")
  }
  else {
    write.csv(data, string, ...)
  }
}
